include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    library_private_types_in_public_api: ignore
    unused_catch_stack: error
    unused_import: warning
    unused_local_variable: error

custom_lint:
  rules:
    - no_num_types: true

linter:
  rules:
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_use_package_imports: true
    annotate_overrides: true
    avoid_dynamic_calls: true
    avoid_print: true
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_void: true
    avoid_single_cascade_in_expression_statements: true
    avoid_unused_constructor_parameters: true
    camel_case_types: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    empty_constructor_bodies: true
    omit_local_variable_types: true
    parameter_assignments: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_int_literals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_single_quotes: true
    prefer_typing_uninitialized_variables: true
    require_trailing_commas: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_new: true
    unnecessary_parenthesis: true
    unnecessary_this: true
    use_named_constants: true
