name: ll_design_system
description: "A new Flutter package project."
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  assets:
    path: assets
  flutter_svg: ^2.0.16
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
#flutter:
#  assets:
#    - assets/icons/
